{{- with .Values -}}
{{ if .enable.configmap }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .name }}-configmap
  namespace: {{ .namespace }}
data:
{{- .extensions | toYaml | nindent 2 }}
{{ end }}
{{- end -}}