{{- with .Values -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: f8s
  namespace: {{ .namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .deployment.repository }}:{{ .deployment.image_tag }}"
          imagePullPolicy: {{ .deployment.image_pull_policy }}
          command: []
          args: []
          resources:
            requests:
              memory: {{ .deployment.memory }}
              cpu: {{ .deployment.cpu }}
          envFrom:
            {{- if .enable.secret }}
            - secretRef:
                name: {{ .name }}-secret
            {{- end }}
          ports:
            - containerPort: {{ .service.target_port }}
          {{- if .enable.liveness_probe }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .service.target_port }}
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          {{- end }}
          {{- if .enable.readiness_probe }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .service.target_port }}
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 5
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/f8s-config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ .name }}-configmap
{{- end -}}
