{{- with .Values -}}
{{ if .enable.nginx_ingress }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .name }}-nginx-ingress
  namespace: {{ .namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - host: {{ .nginx_ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}-service
                port:
                  number: 80
{{ end }}
{{- end -}}