{{- with .Values -}}
{{ if .enable.secret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .name }}-secret
  namespace: {{ .namespace }}
type: Opaque
data:
{{- .secret | toYaml | nindent 2 }}
{{ end }}
{{- end -}}