{{- with .Values -}}
{{ if .enable.secret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .name }}-secret
  namespace: {{ .namespace }}
type: Opaque
stringData:
{{- $dir := .deployment.config_directory -}}
{{- range $key, $value := .extensions }}
  {{ upper $key }}_CONFIG_PATH: {{ $dir }}/{{ $key }}-config.yaml
{{- end }}
{{- .secret | nindent 2 }}
{{ end }}
{{- end -}}