{{- with .Values -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .name }}-service
  namespace: {{ .namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.target_port }}
{{- end -}}