{{- with .Values -}}
{{ if .enable.traefik_ingress }}
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: {{ .name }}-ingress
  namespace: {{ .namespace }}
spec:
  routes:
    - match: {{ .traefik_ingress.match }}
      kind: Rule
      services:
        - name: {{ .name }}-service
          kind: Service
          port: 80
{{ end }}
{{- end -}}