name: f8s
namespace: f8s

enable:
  namespace: false
  configmap: true
  secret: true
  nginx_ingress: false
  traefik_ingress: false
  readiness_probe: true
  liveness_probe: true

extensions:
  f8s: "{}"

deployment:
  repository: # your f8s repo
  image_tag: # your f8s image tag
  image_pull_policy: IfNotPresent
  memory: 128Mi
  cpu: 200m
  config_directory: /etc

service:
  port: 80
  target_port: 8080

nginx_ingress:
  host: ""

# Example: Host(`f8s.k8s-cluster.com`)
traefik_ingress:
  match: ""
